version: '3'

volumes:
  postgres_data: {}
  caddy: {}

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - $HOME/postgresql_baks/:/backups:rw
    env_file: ./env/prod.env

  redis:
    image: redis:latest

  django:
    container_name: django
    # restart: always
    build:
      context: .
      dockerfile: compose/django/production/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app:rw
    env_file: ./env/prod.env
    command: /gunicorn.sh

  webserver:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    container_name: webserver
    volumes:
      - ./.var/django.sock:/var/run/django.sock:rw
      - ./staticfiles/:/usr/share/nginx/html/static/:ro
      - ./media/:/usr/share/nginx/html/media/:rw
    environment:
      VIRTUAL_HOST: empathise.co
      LETSENCRYPT_HOST: empathise.co
      LETSENCRYPT_EMAIL: panuta@gmail.com

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d:rw
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d:rw
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html:rw
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d:rw
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d:rw
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html:rw
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d:rw
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d:rw
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html:rw
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-proxy

networks:
  default:
    external:
      name: webproxy
