FROM nginx:stable-alpine

COPY ./compose/nginx/nginx.conf /etc/nginx/nginx.conf

# VOLUME /var/run/django.sock
# RUN chown nginx:nginx /var/run/django.sock

# VOLUME /usr/share/nginx/html/static/
# VOLUME /usr/share/nginx/html/media/
